Description:
  Main Template

Metadata:
  AWS::CloudFormation::Interface:
    ParameterGroups:
    - Label:
        default: General configuration
      Parameters:
        - Environment
        - BucketName
    - Label:
        default: VPC configuration
      Parameters:
        - VpcCIDR
  Stack:
    Value: 0
  VersionDate:
    Value: 20160518
  Identifier:
    Value: main
  Input:
    Description: Input of all required parameters in nested stacks
  Output:
    Description: N/A


Parameters:
  BucketName:
    Type: String
    Description: Bucket where the templates are stored.
    AllowedPattern: ^[0-9a-zA-Z]+([0-9a-zA-Z-.]*[0-9a-zA-Z])*$
    ConstraintDescription: Quick Start bucket name can include numbers, lowercase
      letters, uppercase letters, periods (.), and hyphens (-). It cannot start or
      end with a hyphen (-).
  KeyName:
    Type: AWS::EC2::KeyPair::KeyName
    Default: eu-west-1
    Description: AWS Keypair for instances SSH. If you select Fargate in the ClusterType, this field will not take effect.
  VpcCIDR:
    AllowedPattern: '((\d{1,3})\.){3}\d{1,3}/\d{1,2}'
    Default: 10.40.0.0/16
    Description: VPC CIDR Block (eg 10.0.0.0/16)
    Type: String
  InstanceTypeRDS:
    Type: String
    Default: db.t2.micro
    Description: RDS instance size.
    AllowedValues:
      - db.t2.micro
      - db.t2.medium
      - db.m4.large
      - db.m4.xlarge
      - db.r4.large
      - db.r4.xlarge
  InstanceTypeEC2:
    Type: String
    Default: t2.micro
    AllowedValues:
      - t2.medium
      - t2.micro
      - t2.large
      - m4.large
      - m4.xlarge
      - c4.large
      - c4.xlarge
    Description: If you select Fargate in the ClusterType, this field will not take effect.
  Environment:
    Type: String
    Default: development
    AllowedValues:
      - development
      - production
    Description: Environment Name - This is used like a suffix for many resources.
  DatabaseUsername:
    Type: String
    NoEcho: true
    Description: Specify a username for your RDS
    Default: af2018dbuser
  DatabasePassword:
    Type: String
    NoEcho: true
    Description: Database user password (Change it)
    Default: dbpassafdev2018#

Mappings:
  Shortname:
    development:
      val: dev
    production:
      val: prod

Resources:
  VPC:
    Type: AWS::CloudFormation::Stack
    Properties:
      TemplateURL: !Sub https://s3.amazonaws.com/${BucketName}/network/vpc.yml
      TimeoutInMinutes: '60'
      Parameters:
        EnvironmentName: !Ref Environment
        VpcCIDR: !Ref VpcCIDR

  Wordpress:
    Type: AWS::CloudFormation::Stack
    Properties:
      TemplateURL: !Sub https://s3.amazonaws.com/${BucketName}/application/wordpress.yml
      TimeoutInMinutes: '60'
      Parameters:
        SubnetId: !GetAtt VPC.Outputs.PublicSubnet1
        VPC: !GetAtt VPC.Outputs.VPC
        KeyName: !Ref KeyName
        DBName: mysql
        DBHost: !GetAtt RDS.Outputs.DatabaseDNS
        DBPassword: !Ref DatabasePassword
        DBUser: !Ref DatabaseUsername
        InstanceType: !Ref InstanceTypeEC2
        StackName: !Ref AWS::StackName

  RDS:
    Type: AWS::CloudFormation::Stack
    Properties:
      TemplateURL: !Sub https://s3.amazonaws.com/${BucketName}/datastore/rds.yml
      TimeoutInMinutes: '60'
      Parameters:
        Environment: !Ref Environment
        Engine: "mysql"
        EngineVersion: "5.7.22"
        InstanceName: !Sub
          - ${AWS::StackName}-${Env}
          - Env: !FindInMap [Shortname, !Ref Environment, val]
        InstanceType: !Ref InstanceTypeRDS
        Username: !Ref DatabaseUsername
        Password: !Ref DatabasePassword
        Storage: 200
        SubnetIds: !GetAtt VPC.Outputs.PrivateSubnets
        VpcCidr: !GetAtt VPC.Outputs.VpcCIDR
        VpcId: !GetAtt VPC.Outputs.VPC

Outputs:
  Wordpress:
    Value: !GetAtt Wordpress.Outputs.Wordpress
